#!/bin/bash

#SBATCH -J coupling_selsunda2               # Job name
#SBATCH -o coupling_selsunda2.log         # Name of stdout output file (%j expands to jobId)
#SBATCH -N 2                  # Total number of nodes requested
#SBATCH -n 166                # Total number of mpi tasks requested
#SBATCH -t 24:00:00           # Run time (hh:mm:ss) - 1.5 hours
#SBATCH -p normal             # Partition name

# Launch MPI-based executable
mpirun ./coawstM coupling_selsunda2.in > coupling_selsunda2.out
